name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true
    - name: Load cached venv
      id: cached-poetry-venv
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ matrix.python-version }}-${{ hashFiles('poetry.lock') }}
    - name: Install dependencies
      if: steps.cached-poetry-venv.outputs.cache-hit != 'true'
      run: poetry install
    - name: Run tests
      run: poetry run pytest --cov --cov-report=xml
    - name: Check coverage greater than 95%
      run: |
        COVERAGE=$(grep -oP 'line-rate="\K(1|0.\d+)' coverage.xml | head -n 1)
        exit $(echo "$COVERAGE <= 0.95" | bc -l)
    - name: Type checker
      run: poetry run mypy codestripper
    

